### PR TITLE
Email generation improvements

### PR DESCRIPTION
**Pull request by dmitrijivanenko**
Cleaned the email generation function. Added two more for male/female emails generations.

### CODE REVIEW

**Comment by dmitrijivanenko** [comment]
Regarding the travis, in logs there is nothing to investigate, just "signal: killed" without errors. Locally all tested are passed

**Comment by dmitrijivanenko** [comment]
regarding this one https://stackoverflow.com/questions/43100127/golang-error-while-make-test-signal-killed i have changed go version in .travis.yml so the first test is passed the second one is failed again

https://travis-ci.org/malisit/kolpa/builds/258931762?utm_source=github_status&utm_medium=notification

**Comment by malisit** [comment]
We can remove master from `.travis.yml`. It's not a must have. Can you do it, so that I can merge them as a whole?

**Comment by malisit** [comment]
Well, there is a problem with Travis CI clearly. I'll merge this one anyways. Thanks!

**Pull request merged**
