### PR TITLE
Email generation improvement, Gender, Person generation functions

### PR DESCRIPTION
**Pull request by dmitrijivanenko**
Hello, have improved email generation function, added possible ways to generate male/female email addresses. Added the Gender generation function, and a wrapper as Person for the First Name, Last Name, Gender, Address, Email, Phone, - so we can generate a Person with random fields. All new code is 100% covered with tests.

### CODE REVIEW

**Comment by malisit** [comment]
Even though the person generation idea is good, I think wrapping around the GenericGenerator is kind of missing the whole point of GenericGenerator itself.
I think this should be done by just providing data files. Having a struct for a person can be left to developer.
`{{name}}, {{gender}}, {{email}}, {{address}}, {{phone}}` must be enough.

**Comment by dmitrijivanenko** [comment]
But then it is not so comfortable to work with this generated Person, couse it is just a string, may be we can return a map? Also, we can have a function which can return a Person as a string or sliced map[string]string with data depending on developer need? What do you think?

**Comment by malisit** [comment]
In general, I think, the use case changes depend on the developer who uses this package and we cannot unriddle all possible use cases. What if a dev does not want to have address in the person struct but does want to have random datetime with it? We already give the opportunity to generate every one of the instances a person can get. So, let them deal with other stuff. If they just want to have the person in your way, they are free to do so by implementing their own person struct.

**Comment by dmitrijivanenko** [comment]
I have cleaned this PR from person generation function, now it has only gender generation and some email generation function improvement.

**Comment by malisit** [comment]
I could not have the chance to check what's wrong but build has failed. Can you please debug it?

**Comment by dmitrijivanenko** [comment]
Regarding the travis, seems somethign went wrong with build, but i have not access to restart it. All test are passed locally

**Comment by dmitrijivanenko** [comment]
It is very strange, couse travis log says nothing exept the "signal was killed" , but locally all tests are passing, may be i will create later from scratch a new PR, so im closing this one

**Comment by malisit** [comment]
I couldn't understand either. Alright, I'll be waiting for it. Thanks!

**Pull request closed without merging**
