### PR TITLE
Change all absolute paths that use go path to relative ones

### PR DESCRIPTION
**Pull request by maciekmm**
I removed all occurances of basing directory off of GOPATH, relative paths should work fine and allow custom languages to be added to data folder relative to the application using this library.

### CODE REVIEW

**Comment by maciekmm** [comment]
This introducec one problem, you have to copy the data folder. 
The problem with the previous solution was that the application using this particular library would work only on dev machine.

**Comment by malisit** [comment]
Can you elaborate on how the previous solution were to only work on dev machine?

**Comment by maciekmm** [comment]
@malisit In case the application that uses this library is compiled and distributed, the ./data folder has to be distributed with the binary. Having it sourced from the GOPATH is a bad idea, because:
- machine might not have a Go environment and therefore no GOPATH
- machine might have multiple entries in the GOPATH
In both of these cases the application would not work on the client machine, but would work perfectly on the dev machine.

Assuming the library is compiled on the machine that has appropriate go toolchain, one GOPATH entry, and this library (if those 3 conditions are not met the application does not work regardless), the execution will not work after this change, because the ./data folder has to be placed in the folder along side the executable.

The best solution would be to include the ./data inside the library source maybe using `go generate`. Another solution would be to add appropriate message to the readme.

**Comment by malisit** [comment]
Alright, thanks for explanation. I'll merge this one. If you would like to enhance things about the data access, feel free to shoot another PR. Thanks.

**Pull request merged**
